using Tyuiu.UlukhanovDV.Sprint1.Task2.V12.Lib;
// See https://aka.ms/new-console-template for more information
DataService ds = new DataService();
Console.Title = "Спринт #1 | Выполнил: Улуханов Д. В. | СМАРТб-25-1";
Console.WriteLine("****************************************************************************");
Console.WriteLine("* Спринт #1                                                                *");
Console.WriteLine("* Тема: Арифметические операторы в C#                                      *");
Console.WriteLine("* Задание #2                                                               *");
Console.WriteLine("* Вариант #12                                                              *");
Console.WriteLine("* Выполнил: Улуханов Джабраил Вагифович | СМАРТб-25-1                      *");
Console.WriteLine("****************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                 *");
Console.WriteLine("* Написать программу, которая запрашивает у пользователя исходные данные,  *");
Console.WriteLine("* выполняет указанные расчёты и печатает результат на экране.              *");
Console.WriteLine("*                                                                          *");
Console.WriteLine("****************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                         *");
Console.WriteLine("****************************************************************************");
int value;
Console.WriteLine("Введите значение volue:");
value = Convert.ToInt32(Console.ReadLine());
int valueTwo;
Console.WriteLine("Введите значение volueTwo:");
valueTwo = Convert.ToInt32(Console.ReadLine());
int valueThree;
Console.WriteLine("Введите значение volueThree:");
valueThree = Convert.ToInt32(Console.ReadLine());

Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ                                                               *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("Объём параллелепипеда = " + ds.CalculateParallelepipedVolume(value, valueTwo, valueThree));
Console.ReadLine();